version: "3.7"
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    networks:
      - jenkins_nw
    command:
      - --configFile=/configuration/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /etc/ssl/mycerts:/etc/ssl/mycerts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/configuration:/configuration:ro

  welcome:
    container_name: welcome_server
    restart: always
    image: httpd:2.4-alpine
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
    networks:
      - jenkins_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welcome.rule=Host(`mercury.andrena.de`)"
      - "traefik.http.routers.welcome.entrypoints=websecure"
      - "traefik.http.routers.welcome.tls=true"
      - "traefik.http.routers.welcome.service=welcome"
      - "traefik.http.services.welcome.loadbalancer.server.port=80"

  jenkins:
    container_name: jenkins
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    environment:
        FLUENTD_HOST: fluentd
        FLUENTD_PORT: 24224
        TENANT: "jenkins"
        ACCESS_KEY: ${ACCESS_KEY}
        SECRET_KEY: ${SECRET_KEY}
    volumes:
      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins-admin-password
    networks:
      - jenkins_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins-mercury.andrena.de`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - http.port=9200
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - jenkins_nw
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - jenkins

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    restart: always
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - jenkins_nw
    depends_on:
      - es01
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana-mercury.andrena.de`)"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.tls=true"
      - "traefik.http.routers.kibana.service=kibana"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"


  fluentd:
    image: ericnaglertw/cd4ml-fluentd:1
    restart: always
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - jenkins_nw
    depends_on:
      - es01

  cd4ml:
    build:
      context: .
      dockerfile: Dockerfile-model
    container_name: cd4ml
    restart: always
    environment:
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - jenkins_nw
    depends_on:
      - fluentd
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cd4ml.rule=Host(`cd4ml-mercury.andrena.de`)"
      - "traefik.http.routers.cd4ml.entrypoints=websecure"
      - "traefik.http.routers.cd4ml.tls=true"
      - "traefik.http.routers.cd4ml.service=cd4ml"
      - "traefik.http.services.cd4ml.loadbalancer.server.port=5005"

  minio:
    image: minio/minio:RELEASE.2022-01-27T03-53-02Z
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SECRET_KEY}
    entrypoint: sh
    command: -c 'mkdir -p /data/cd4ml-ml-flow-bucket && minio server /data --console-address :9001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-storage:/data
    networks:
      - jenkins_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio-mercury.andrena.de`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"

  mlflow:
    container_name: mlflow
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SECRET_KEY}
    networks:
      - jenkins_nw
    volumes:
      - mlflow-storage:/mnt/mlflow
    depends_on:
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow.rule=Host(`mlflow-mercury.andrena.de`)"
      - "traefik.http.routers.mlflow.entrypoints=websecure"
      - "traefik.http.routers.mlflow.tls=true"
      - "traefik.http.routers.mlflow.service=mlflow"
      - "traefik.http.services.mlflow.loadbalancer.server.port=5000"

volumes:
  jenkins_home:
    driver: local
  data01:
    driver: local
  minio-storage:
    driver: local
  mlflow-storage:
    driver: local

networks:
  jenkins_nw:

secrets:
  jenkins-admin-password:
    file: ./jenkins/jenkins-admin-password.txt